wdb_cantaloupe_auth.settings:
  type: config_object
  label: 'WDB Cantaloupe auth settings'
  mapping:
    token_ttl:
      type: integer
      label: 'Token lifetime (seconds)'
    token_param:
      type: string
      label: 'Query parameter name for IIIF tokens'
